server:
  port: 19081
knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routes:
      - name: 测试分组1
        uri: knife4j.xiaominfo.com
        location: /v2/api-docs?group=2.X版本
      - name: 测试分组2
        uri: knife4j.xiaominfo.com
        location: /v2/api-docs?group=3.默认接口
      - name: 测试分组3
        uri: 192.168.0.51:8080
        location: /api/multistage/v2/api-docs?group=version2.0
      - name: 测试分组4
        uri: 192.168.4.51:2312
        location: /api/v2/api-docs
